package free5gc.ngap.ngapType

class ProtocolIESingleContainerAMFPagingTargetExtIEs

class ProtocolIESingleContainerBroadcastCancelledAreaListExtIEs

class ProtocolIESingleContainerBroadcastCompletedAreaListExtIEs

class ProtocolIESingleContainerCauseExtIEs

class ProtocolIESingleContainerCellIDListForRestartExtIEs

class ProtocolIESingleContainerCPTransportLayerInformationExtIEs

class ProtocolIESingleContainerDRBStatusDLExtIEs

class ProtocolIESingleContainerDRBStatusULExtIEs

class ProtocolIESingleContainerGlobalRANNodeIDExtIEs

class ProtocolIESingleContainerGNBIDExtIEs

class ProtocolIESingleContainerLastVisitedCellInformationExtIEs

class ProtocolIESingleContainerN3IWFIDExtIEs

class ProtocolIESingleContainerNgENBIDExtIEs

class ProtocolIESingleContainerNGRANCGIExtIEs

class ProtocolIESingleContainerOverloadResponseExtIEs

class ProtocolIESingleContainerPWSFailedCellIDListExtIEs

class ProtocolIESingleContainerQosCharacteristicsExtIEs

class ProtocolIESingleContainerResetTypeExtIEs

class ProtocolIESingleContainerSONInformationExtIEs

class ProtocolIESingleContainerTargetIDExtIEs

class ProtocolIESingleContainerUEIdentityIndexValueExtIEs

class ProtocolIESingleContainerUENGAPIDsExtIEs

class ProtocolIESingleContainerUEPagingIdentityExtIEs

class ProtocolIESingleContainerUPTransportLayerInformationExtIEs

class ProtocolIESingleContainerUserLocationInformationExtIEs

class ProtocolIESingleContainerWarningAreaListExtIEs


